---
title: Intro to Bivalves
author: Katie S. Collins
date: '2019-06-29'
slug: getting-started-with-bivalves
categories: []
tags:
  - Bivalvia
  - overview
---

If you've ever been beach-combing, anywhere in the world, chances are you've picked up bivalve shells. Bivalves are a group of animals that includes familiar things like scallops, oysters, mussels, clams and cockles. 

(If you already know what a bivalve is and how Linnaean taxonomy works, you can safely skip this post!)

The defining character of the group is that they have two shells - other kinds of mollusc have one, or eight, or none - hence *bi* (two) *valve* (shell). Often though, you'll only find one valve. Bivalves hold their shells together around their bodies using a set of muscles that act against a springy ligament, and when they die, those muscles relax, the ligament does what it does best, and the shell pops open. After that happens, the two valves fall apart pretty quickly. 

So you've found a shell on the beach and you'd like to know what kind of a bivalve it came from! That's a noble goal. I'm not just saying that because I spend all day telling shells apart and I want to feel justified in my choices (... okay, I am a *little* bit ...). It's also not as difficult as you might think. I'm here to help!

There are over six thousand species of bivalves in the ocean today, though, and they don't all live everywhere. I haven't seen all of them, either (although I've seen a lot of them!). But fortunately, the task of identifying a living thing is a hierarchical problem. We can narrow down the search pretty easily with only a few questions, and then hopefully you will be able to find a local guidebook or website that will take you further. I'll also be doing posts on different subgroups, common mistakes in identification, and maybe even addressing questions if anyone asks me any! (If you have a burning question and need an ID ASAP, feel free to [tweet me](https://www.twitter.com/spissatella))

First off though, we need to understand a little bit about this hierarchical system nonsense. 

Bivalves are a **class** of molluscs under the Linnaean system. The formal way to refer to them is as **Class Bivalvia**. (Other classes are Gastropoda (snails and slugs), Cephalopoda (Nautilus, Octopus, Squid and the extinct Ammonites), Polyplacophora (chitons), and a few others. We'll cover Gastropoda on this blog too eventually.) Classes are technically subdivided into Orders, which are subdivided into Families, which are subdivided into Genera (singular: Genus), which are subdivided into Species. If you're a person who has done any biology in school, you probably remember this. (If you think maybe you *should* remember it but you don't, don't worry - it's not exactly vital to your day to day life! You can always come back here and look it up again.)

The Orders in Bivalvia are sort of under dispute, however - the only one that most people formally agree upon is a very interesting set of animals called the Anomalodesmata. The rest of them are hotly debated. I don't have a particular horse in this race so for the purposes of having some kind of handle on what to call the larger groups, I'll be using the names following the Bivalve Tree of Life project. That splits Bivalvia up at the coarsest level into *clades* (clade is just a fancy biology word for 'a group of animals that are all more closely related to each other than they are to anything outside the clade'), Protobranchia, Pteriomorpha, Paleoheterodonta, Archiheterodonta, and Imparidentia. Each of these groups has some fundamental characteristics that we can use to assign specimens to the right higher group. 

Within these higher clades, bivalves are split into families. Family-level assignment is, for the most part, pretty stable. And just like the higher clades, there are features of the shell that help us recognise what family a specimen should belong to. 

Identifying things to genus and then to species gets a little bit more tricky, but we'll get there! 

The next post will be about the higher clades - so go grab the shells you've been puzzling over, and we'll see if we can sort them out. 
